apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: container1
      image: nginx




############ kubectl apply -f  pod.yaml ###############
#kubectl get pods
#kubectl delete pod pod-name
